apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8080 # matching to container port
      nodePort: 31000
  selector:
    app: backend-app
