apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URI
          value: {{ .Values.backend.redisUri }}