apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
